#!/usr/bin/env python3
import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


def main():
    parser = argparse.ArgumentParser(description="Plot CIFAR10 comparison including typiclust_dinov2.")
    parser.add_argument(
        "--summary_csv",
        type=Path,
        default=Path("/home/jiayuan/TypiClust/output/CIFAR10/resnet18/summary/all_groups_summary.csv"),
        help="Path to all_groups_summary.csv generated by summarize_accuracy_vs_budget.py",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("/home/jiayuan/TypiClust/output/CIFAR10/resnet18/summary/compare_typiclust_dinov2.png"),
        help="Output png path",
    )
    parser.add_argument(
        "--methods",
        nargs="+",
        default=[
            "random",
            "uncertainty",
            "entropy",
            "margin",
            "coreset",
            "typiclust_rp",
            "typiclust_lejepa",
            "typiclust_dinov2",
        ],
        help="Methods to include in comparison",
    )
    args = parser.parse_args()

    df = pd.read_csv(args.summary_csv)
    keep = df[df["method"].isin(args.methods)].copy()
    if keep.empty:
        raise RuntimeError(f"No selected methods found in {args.summary_csv}")

    fig, ax = plt.subplots(figsize=(11, 6))
    for method in args.methods:
        sub = keep[keep["method"] == method].sort_values("labeled_budget")
        if sub.empty:
            continue
        ax.plot(
            sub["labeled_budget"].values,
            sub["mean_accuracy"].values,
            marker="o",
            linewidth=2,
            label=method,
        )
        ax.fill_between(
            sub["labeled_budget"].values,
            sub["mean_accuracy"].values - sub["std"].values,
            sub["mean_accuracy"].values + sub["std"].values,
            alpha=0.15,
        )

    ax.set_title("CIFAR10 Accuracy vs Budget (incl. DINOv2 TypiClust)")
    ax.set_xlabel("Labeled budget")
    ax.set_ylabel("Test accuracy")
    ax.grid(alpha=0.3)
    ax.legend(fontsize=9, loc="best")
    fig.tight_layout()
    args.out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(args.out, dpi=200)
    plt.close(fig)
    print(f"Saved: {args.out}")


if __name__ == "__main__":
    main()
